config/routes.rb
Rails.application.routes.draw do

  resources :properties
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Commontator::Engine => '/commontator'

  resources :posts

  devise_for :users
  
  root to: 'pages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_commontable

	#has_many :comments, dependent: :destroy
	#belongs_to :user
end

app/models/property.rb
class Property < ActiveRecord::Base
	geocoded_by :location
  	after_validation :geocode, :if => :location_changed?

  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	validates_presence_of :description
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_commontator

	#has_many :posts, dependent: :destroy
	#has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  #ROLES = {0 => :guest, 1 => :user, 2 => :moderator, 3 => :admin}
  # ROLES = {0 => :user, 1 => :customer, 2 => :admin}

  # attr_reader :role

  # def initialize(role_id = 0)
  #   @role = ROLES.has_key?(role_id.to_i) ? ROLES[role_id.to_i] : ROLES[0]
  # end

  # def role?(role_name)
  #   role == role_name
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_devise_params, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
  end

  def configure_devise_params
  	devise_parameter_sanitizer.for(:sign_up) do |u|
  		u.permit(:first_name, :last_name, :address, :phone, :email, :password, :password_confirmation)
  	end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  # def index
  #   @properties = Property.all
  # end

  def index
    if params[:search].present?
      @properties = Property.near(params[:search])
    else
      @properties = Property.all
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:description, :image, :location, :latitude, :longitude, :amenties, :facilities, :date, :price, :services)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
		content_for(:header) { text.to_s }
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "devise", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",	 root_path %></li>
          <li><%= link_to "Post",	 post_path %></li>
          <li><%= link_to "User", new_user_session_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <%= link_to "User Logout", destroy_user_session_path, :method => :delete %>
          <% else %>
            <% if user_signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                  </li>
                </ul>
              </li>
              <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to "Profile", edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'formtastic' %>
  <!--[if IE 6]>--><%= stylesheet_link_tag 'ie6' %>
  <!--[if IE 7]>--><%= stylesheet_link_tag 'ie7' %>
  <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
  <%= javascript_include_tag 'jquery.geocomplete.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--For Header with Login Logout And SignUp Start-->
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Project', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <li><%= link_to 'Post', posts_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.first_name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!--For Header with Login Logout And SignUp End-->
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>

  <%= yield %>

</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <% if user_signed_in? %>
        <div class="jumbotron">
            <div class="container">
              <h1>Welcome! <%= current_user.first_name %></h1>
              <p>
                website Is Under Construction...!
              </p>
              <p>
                Please Check Back Soon.
              </p>
            </div>
          </div>
        <% else %>
          <div class="jumbotron">
            <div class="container">
              <h1>Welcome!</h1>
              <p>Register to get started.</p>
              <p>
                <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
              </p>
            </div>
          </div>
  <% end %>
  
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <%= f.submit "Submit", style: 'margin-bottom:20px' ,class: 'btn btn-success' %>
<% end %>

app/views/posts/edit.html.erb
<% header "Editing Post" %>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'btn btn-primary' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-info' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% header "Listing Posts" %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-xs' %></td>
      </tr>
        <%#= commontator_thread(post) %>
    <% end %>
  </tbody>
</table>

<br>
<%#= link_to 'New Post', new_post_path, class: 'btn btn-success' %>
<%= link_to new_post_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Post
<% end %>

app/views/posts/new.html.erb
<% header "New Post" %>
<%= render 'form' %>

<%= link_to 'Back', posts_path, class: 'btn btn-info' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Comments:</strong>
  <%#= @post.body %><%= commontator_thread(@post) %>
</p>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-info' %>

app/views/properties/_form.html.erb
<%= semantic_form_for @property do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :description, input_html: { rows: 10, cols: 25 }, hint: 'Make it a good one' %>
    <%= f.file_field :image %><br>
    <%= f.input :location %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :amenties, :as => :radio %>
    <%= f.input :facilities %>
    <%= f.input :date %>
    <%= f.input :price %>
    <%= f.input :services %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input, :class => "primary" %>
  <% end %>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image</th>
      <th>Location</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Amenties</th>
      <th>Facilities</th>
      <th>Date</th>
      <th>Price</th>
      <th>Services</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <h1>Properties Finder</h1>
  <%= form_tag properties_path, :method => :get do %>
    <p>
      <%= text_field_tag :search, params[:search],:id => 'geo-input' %>
      <%= submit_tag "Search Near", :name => nil %>
    </p>
  <% end %>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.description %></td>
        <td><%= image_tag (property.image.url(:medium)) %></td>        
        <td><%= property.location %></td>
        <!-- <td><%= property.latitude %></td>
        <td><%= property.longitude %></td> -->
        <td><%= property.distance.round(2) %> miles</td>
        <td><%= property.amenties %></td>
        <td><%= property.facilities %></td>
        <td><%= property.date %></td>
        <td><%= property.price %></td>
        <td><%= property.services %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @property.image.url(:medium) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @property.location %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @property.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @property.longitude %>
</p>

<p>
  <strong>Amenties:</strong>
  <%= @property.amenties %>
</p>

<p>
  <strong>Facilities:</strong>
  <%= @property.facilities %>
</p>

<p>
  <strong>Date:</strong>
  <%= @property.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Services:</strong>
  <%= @property.services %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/users/shared/_links.html.erb
<hr>
<div class="btn-group-vertical">
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-default btn-sm' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-default btn-sm' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'btn btn-default btn-sm' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'btn btn-default btn-sm' %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'btn btn-default btn-sm' %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), class: 'btn btn-default btn-sm' %><br />
  <% end -%>
<% end -%>
</div>